---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
- name: ':boom: breaking change'
  from_name: breaking
  description: Breaking Changes
  color: bfd4f2
- name: ':ghost: bug'
  from_name: bug
  description: Something isn't working
  color: d73a4a
- name: ':building_construction: build'
  from_name: build
  description: Build System and Dependencies
  color: bfdadc
- name: ':construction_worker_woman: ci'
  from_name: ci
  description: Continuous Integration
  color: 4a97d6
- name: ':recycle: dependencies'
  from_name: dependencies
  description: Pull requests that update a dependency file
  color: 0366d6
- name: ':book: documentation'
  from_name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: ':roll_eyes: duplicate'
  from_name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: ':rocket: feature'
  from_name: enhancement
  description: New feature or request
  color: a2eeef
- name: ':clapper: github_actions'
  from_name: github_actions
  description: Pull requests that update Github_actions code
  color: '000000'
- name: ':hatching_chick: good first issue'
  from_name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: ':pray: help wanted'
  from_name: help wanted
  description: Extra attention is needed
  color: '008672'
- name: ':no_entry_sign: invalid'
  from_name: invalid
  description: This doesn't seem right
  color: e4e669
- name: ':racing_car: performance'
  from_name: performance
  description: Performance
  color: '016175'
- name: ':snake: python'
  from_name: python
  description: Pull requests that update Python code
  color: 2b67c6
- name: ':question: question'
  from_name: question
  description: Further information is requested
  color: d876e3
- name: ':sparkles: code quality'
  from_name: code quality
  description: Code quality improvements
  color: ef67c4
- name: ':file_cabinet: deprecation'
  from_name: deprecation
  description: Removals and Deprecations
  color: 9ae7ea
- name: ':nail_care: style'
  from_name: style
  description: Style
  color: c120e5
- name: ':test_tube: testing'
  from_name: testing
  description: Pull request that adds tests
  color: b1fc6f
- name: ':woman_shrugging: wontfix'
  from_name: wontfix
  description: This will not be worked on
  color: ffffff
- name: ':arrow_up: bump'
  description: Bump the version
  color: 3C5D34
- name: ':sparkles: enhancement'
  color: CBF8DA
- name: 'skip-changelog'
  color: D3D3D3
