name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'


categories:
  - title: '⚠️ Breaking changes'
    labels:
      - 'breaking'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '⏳ Deprecations'
    labels:
      - 'deprecation'
  - title: '📃 Documentation'
    labels:
      - 'documentation'
  - title: '🧩 Dependency Updates'
    labels:
      - 'dependencies'
      - 'github_actions'
    collapse-after: 5
  - title: '🧰 Maintenance'
    labels:
      - 'perfomance'
      - 'refactor'
      - 'ci'
      - 'build'
  - title: '🔬 Other updates'
    labels:
      - 'style'
      - 'testing'

autolabeler:
  - label: 'feature'
    title:
      - '/adds/i'
      - '/add method/i'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'code quality'
    title:
      - '/Refactor/i'
  - label: 'testing'
    title:
      - '/test:/i'
      - '/add test/i'
    files:
      - 'test_*'
      - 'conftest.py'
  - label: 'documentation'
    title:
      - '/docs:/i'
    files:
      - '*.md'
      - 'mkdocs.yml'
  - label: 'ci'
    title:
      - '/ci:/i'
    files:
      - '.github/*'
  - label: 'dependencies'
    title:
      - '/bump/i'
  - label: 'deprecation'
    title:
      - '/Deprecate/i'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-contributors:
  - 'tr4nt0r'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'bug'
  default: patch

template: |
  ## Changes

  $CHANGES

  Special thanks to: $CONTRIBUTORS
