site_name: Pynecil
site_description: Python library to communicate with Pinecil V2 soldering irons via Bluetooth

repo_url: https://github.com/tr4nt0r/pynecil
repo_name: tr4nt0r/pynecil

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: purple
          accent: light blue
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: purple
          accent: light blue
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.11/objects.inv
                options:
                    docstring_style: numpy
                    merge_init_into_class: true
                    show_signature: false
                    members_order: source

watch:
    - docs
    - pynecil

nav:
    - About: index.md
    - Contributing: contributing.md
    - Reference:
        - pynecil: reference/pynecil.md
